<?php include_once ('./html/header.php') ?>
<?php include_once ('./pokemons/pokemon.php') ?>
<?php include_once ('./pokemons/carapuce.php') ?>
<?php include_once ('./pokemons/salameche.php') ?>
<?php include_once ('./pokemons/bulbizare.php') ?>
<?php include_once ('./items/use.php') ?>
<?php include_once ('./items/balls/ball.php') ?>
<?php include_once ('./items/balls/pokeball.php') ?>
<?php include_once ('./items/balls/superball.php') ?>
<?php include_once ('./items/balls/hyperball.php') ?>
<?php include_once ('./items/balls/masterball.php') ?>
<?php include_once ('./items/potion/heal.php') ?>
<?php include_once ('./items/potion/potion.php') ?>
<?php include_once ('./items/potion/hyperpotion.php') ?>
<?php include_once ('./items/potion/potionmax.php') ?>
<?php include_once ('./items/potion/superpotion.php') ?>